### ISSUE TITLE
[NOTICE] This repository will be deprecated.

### ISSUE THREAD

**Issue by ghost** [LumaKernel/coquille#1]
Don't worry, I will just rename.
This repository all are written by me and my idea except for `README.md` and the files under public domain .
That's why I think I have the reasonable right to claim licensing by myself.

I am going to rename and license it under the Unlicense.

It will be in around June, 2020.

If someone found the problem about this, please let me know.

Thank you.

**Comment by LumaKernel** [comment]
Sorry for confusing.
New repository is now https://github.com/LumaKernel/coqpit.vim , I will do some changes.
